# Generated by Django 3.2.9 on 2021-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_post',
            field=models.DateField(blank=True, null=True),
        ),
    ]
